wandb_version: 1

device:
  desc: null
  value: cpu
progress:
  desc: null
  value: false
seed:
  desc: null
  value: 0
dir:
  desc: null
  value: ./results
mbsize:
  desc: null
  value: 16
lr:
  desc: null
  value: 0.001
n_hid:
  desc: null
  value: 256
n_layers:
  desc: null
  value: 2
n_train_steps:
  desc: null
  value: 2000
dynamics_lr:
  desc: null
  value: 0.0001
dynamics_hid_dim:
  desc: null
  value: 256
horizon:
  desc: null
  value: 8
ndim:
  desc: null
  value: 2
stick:
  desc: null
  value: 0.25
dev:
  desc: null
  value: cpu
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726092235.519779
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.15.3
      8:
      - 5
